builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- name_template: 'KubeSurvival_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - examples/*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
